### ISSUE TITLE
Towards CRAN

### ISSUE THREAD

**Issue by DavZim** [BZPaper/RTransferEntropy#20]
- check inputs: a la ` if (is.na(x)) stop("this is a stop message"`
- implement tests using `testthat`:  [Testthat example](http://r-pkgs.had.co.nz/tests.html)
- add (fake?) data

**Comment by DavZim** [comment]
Travis-CI (continuous integration) mag uns grade noch nicht (siehe https://travis-ci.org/BZPaper/RTransferEntropy), das schau ich mir noch an, dass das Package da richtig durchläuft (das kann bei CRAN auch kommen), dann schicke ich Thomas die tar-files.

**Comment by DavZim** [comment]
Für den Resubmit müssen wir die run-time der Beispiele (die die wir in `?transfer_entropy` sehen) auf unter 5 secs reduzieren.
Ich hab da jetzt mal rumgespielt und wir kommen auf unter 5 secs wenn wir nicht alle Möglichkeiten aufführen (sowas wie Beispiele für die Anzahl der Shuffles raus lassen) aber der wichtigste Punkt ist die Länge der TS. Ist es da möglich auf 500 anstelle von 1.000 zu gehen?

**Comment by FjP80** [comment]
Dann haben wir nur noch 25 Beobachtungen in jedem tail bei 5/95, das könnte dann schwierig mit der Signifikanz werden, kannst Du es mal versuchen und schauen ob die Ergebnisse trotzdem passen?

**Comment by DavZim** [comment]
Die Ergebnisse sind noch Signifikant: https://puu.sh/ARLt8/c40e858496.png

**Comment by FjP80** [comment]
Na dann machen wir es so...wenns denn unbedingt unter 5 s sein muss, haben wir ja keine andre Wahl

**Comment by LeeHaoyu** [comment]
Die Zeit, die die Vignette zum kompilieren braucht ist für CRAN dann irrelevant? Also, es geht insgesamt nur um die Beispiele von ?RTransferEntropy? Ansonsten müssten wir auch nochmal an die Vignette dran...

**Comment by LeeHaoyu** [comment]
Gibt wohl noch Probleme mit der run-time. "checking CRAN incoming feasibility ... NOTE" sollte dagegen kein Problem sein: https://stackoverflow.com/questions/23829978/checking-cran-incoming-feasibility-note-maintainer

**Comment by DavZim** [comment]
Das Windows Issues (related to speed) hängt daran, dass unter Windows strings in Cpp viel langsamer concatenated werden... Suche morgen mal weiter nach ner Möglichkeit das ganze schneller zu machen.

**Comment by DavZim** [comment]
Vignette braucht ńoch zu lange zum kompilieren.
Was können wir daraus kürzen? Brauchen wir zB den Renyi->Shannon Plot mit den Stocks (wir zeigen das ja schon mit den simulierten Daten.

Brauchen wir wirklich die Financial Application für 10 Stocks, oder reichen auch 5?

Weiterhin sollten wir in der Vignette noch mittels Überschriften die verschiedenen simulierten Zeitreihen trennen.

**Comment by dimpflth** [comment]
Ich denke, wir könne auf einen Stock ggf auch runter gehen, es soll ja nur eine Illustration sein. Die vielen Anwendungen usw. können dann ja in das JSS paper wandern. Bei Renyi ist halt die Frage, was man überhaupt noch zeigen will, wenn wir das für ganz wenige machen. Aber da brauchen wir ja keinen Bootstrap, nur die TE für die verschiedenen Quantile. Und vielleicht einfach für die Vignette die Daten nochmal kürzen.
 

Gesendet: Mittwoch, 11. Juli 2018 um 19:42 Uhr
Von: DavZim <notifications@github.com>
An: BZPaper/RTransferEntropy <RTransferEntropy@noreply.github.com>
Cc: dimpflth <thomas.dimpfl@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [BZPaper/RTransferEntropy] Towards CRAN (#20)


Vignette braucht ńoch zu lange zum kompilieren.
Was können wir daraus kürzen? Brauchen wir zB den Renyi->Shannon Plot mit den Stocks (wir zeigen das ja schon mit den simulierten Daten.

Brauchen wir wirklich die Financial Application für 10 Stocks, oder reichen auch 5?

Weiterhin sollten wir in der Vignette noch mittels Überschriften die verschiedenen simulierten Zeitreihen trennen.

**Comment by LeeHaoyu** [comment]
Wenn der Code in der Vignette nicht wichtig ist für CRAN, sondern nur die Zeit, die die Vignette zum kompilieren braucht, warum fügen wir den Code nicht ein, ohne ihn zu kompilieren und setzen die fertigen Plots und TE Fun Outputs dahinter? Falls CRAN nur das Package und die Beispiele von ?RTransferEntropy testest, dann ist der Code in der Vignette doch nicht relant, oder? Damit wäre die Vignette ja schnell kompiliert...

**Comment by DavZim** [comment]
Ich hab jetzt die Runtime der Vignette auf unter 1 min reduziert. Das ist vor allem dadurch erreicht, dass wir die ete's ausweisen ohne CIs (wir können also `calc_ete` anstelle von `transfer_entropy` verwenden). Dementsprechend haben wir in der Financial Application mit allen Stocks keine CIs.

Ich hab auch mal die Interpretationen in der Vignette angepasst. Wir callen immer `transfer_entropy(df$ret, df$sp500)` (also X := Stock, Y := Market) sagen dann aber X->Y := Flow towards Stock. (Wenn das so richtig wäre, bitte Bescheid geben, dann änder ich das wieder).

Zuletzt, könnt ihr euch nochmal kurz die Vignette durchlesen ob ich was übersehen hab. Vor allem, macht es Sinn, dass wir die Verteilungen (Density Plots) für die verschiedenen Stocks in eine Verteilung schmeißen. Ich hab das jetzt mal zu Line-Charts geändert (siehe: https://puu.sh/AUMyI/4e97f79114.png)

**Comment by LeeHaoyu** [comment]
Ich verstehe aber immer noch nicht, warum wir nicht einfach den Code hard coded einfügen und dann die fertigen Grafiken bzw. Outputs. Ich habe bei CRAN nirgends gelesen, dass das nicht erlaubt ist...

**Comment by DavZim** [comment]
@dimpflth bisher hatten wir so einen Plot: https://puu.sh/AV96l/e6e9fb185f.png
Jetzt haben wir den Plot: https://puu.sh/AUMyI/4e97f79114.png

**Comment by LeeHaoyu** [comment]
Wäre gut, wenn nochmal jeder die Vignette liest und ihr/sein OK geben könnte @DavZim @dimpflth @FjP80

**Comment by LeeHaoyu** [comment]
Ich habe noch Typos gefunden, die zu Verwirrungen führen...arbeite grad an dem Rmd File...

**Comment by LeeHaoyu** [comment]
So, ich habe ein kleines Update gemacht und einige Typos und falsche Formulierungen ausgebessert. Das Finance-Beispiel ist verwirrend, da stimmt im Text was nicht ("However, the information flow from the market to the stocks is higher for most stocks than the other direction." passt nicht zum Plot). Das Beispiel bitte nochmal checken.

**Comment by DavZim** [comment]
Beispiel ist geupdated

**Comment by LeeHaoyu** [comment]
Gibt es noch weitere Punkte oder ist jeder zufrieden mit der Vignette?

**Comment by dimpflth** [comment]
erster Absatz: was ist "time-asymmetric information transfer"?

Ansonsten hab ich ein paar kleine redaktionelle Änderungen vorgenommen und wäre ansonsten zufrieden damit.

**Comment by LeeHaoyu** [comment]
Gute Frage, was ist damit gemeint @FjP80 ? Sollen wir das drin lassen, genauer erklären oder umschreiben?

**Comment by dimpflth** [comment]
"time" ist raus. Es klang so beim nochmaligen Lesen, als ob die Zeit auch mal rückwärts laufen könnte, was ja nicht ausgeschlossen ist, aber dafür reicht unsere Physik wohl nicht

**Comment by LeeHaoyu** [comment]
Ok, dann können wir ja schauen, ob CRAN das Package jetzt mag ;)
