### ISSUE TITLE
Add additional extractor functions

### ISSUE THREAD

**Issue by DavZim** [BZPaper/RTransferEntropy#46]
Add additional extractor functions for

- bootstrap results
- printCoefMat
- observations

Anything that I'm missing?

**Comment by LeeHaoyu** [comment]
p-values, std. err.?

**Comment by LeeHaoyu** [comment]
I think the plot() suggestion from the JSS doesn't make much sense, since transfer_entropy only calculates 2 values that are of interest...

**Comment by DavZim** [comment]
How about a plot of the bootstrapped TEs (if n > 1)

**Comment by LeeHaoyu** [comment]
Hm...we could add a density plot - which users can plot anyway if they can extract the bootstrap results - but what should people do with it? The quantiles are reported so the added value of a plot would be negligible, I think. It would just be a graphical illustration of the significance test, and we have p-values and even stars...my two cents - it's open for discussion ;)

**Comment by DavZim** [comment]
printCoefmap is now used in summary (which is a little different from print now)
