### ISSUE TITLE
Multivariate transfer entropy

### ISSUE THREAD

**Issue by dizcza** [BZPaper/RTransferEntropy#48]
Are you planning to support multivariate transfer entropy between X and Y of any size?
```r
dim(x)
# [1] 2000    5
dim(y)
# [1] 2000    3
t <- transfer_entropy(x, y)
# Error in transfer_entropy(x, y) : x and y must be of same length.
```

**Comment by DavZim** [comment]
Hi dizcza,
currently `RTransferEntropy` works only with vectors, i.e., bivariate TE.

**Comment by dizcza** [comment]
Peculiarly, if the second dimension of X and Y is the same, it "works" in terms of it produces some output value, though if you're saying bivariate only, it's probably just a coincidence.
You can close the issue if you know the package won't support multivariate entropy estimation.
Cheers,
Danylo.
