### ISSUE TITLE
Installing RTransfer Entropy

### ISSUE THREAD

**Issue by Abigail575** [BZPaper/RTransferEntropy#51]
Hello! Trying to install RTransfer Entropy On R version 3.6.1 but get the following error message:

Warning in install.packages :
  package ‘https://CRAN.R-project.org/package=RTransferEntropy’ is not available (for R version 3.6.1)

Any ideas of how to install it?

Many thanks

Abigail

**Comment by DavZim** [comment]
Hi Abigail,
I am not really sure what triggers this issue, I tried installing it on my machine and it works with R version 3.6.2.
Can you upgrade your R version? If not, you can try to install it directly with `devtools::install_github("BZPaper/RTransferEntropy")`

Does that help?

Best
David

**Comment by Abigail575** [comment]
Hi David,

Many thanks for your quick response. I shall try upgrading it and see what happens.

Abigail
