### ISSUE TITLE
Transfer Entropy of Multiple Series

### ISSUE THREAD

**Issue by Abigail575** [BZPaper/RTransferEntropy#52]
Hello again,

I was wondering what the script below would look like if I wanted to calculate the transfer entropy between one time series, x, and each row of a matrix, y (where the number of elements in the rows of y equals that of x)? 

calc_te(x, y, lx = 1, ly = 1, q = 0.1, entropy = "Shannon", shuffles = 100, type = "quantiles", quantiles = c(5, 95), bins = NULL, limits = NULL, burn = 50, seed = NULL, na.rm = TRUE)

Many thanks,

Abigail

**Comment by DavZim** [comment]
Can you include a MWE or a [reprex](https://github.com/tidyverse/reprex)

**Comment by DavZim** [comment]
So far I would assume something like this:
```
res <- apply(y, 2, function(y_) calc_te(x, y_, ...)
```

**Comment by Abigail575** [comment]
Thanks! 
Unfortunately it didn't work. Here is my code:
```
x <- c(1, 2, 3)
y <- matrix (c(2 , 4, 3, 1, 5, 7), nrow =2, ncol =3,byrow = TRUE)
res <- apply(y, 2, function(y_) calc_te(x, y_, lx = 1, ly = 1, q = 0.1, 
                                       entropy = "Shannon", shuffles = 100, type = "quantiles", 
                                       quantiles = c(5, 95), bins = NULL, limits = NULL, burn = 50, seed = NULL, 
                                       na.rm = TRUE))

#>Error message:
#>Error in calc_te_ete("te", x, y, lx = lx, ly = ly, entropy = entropy,  : 
#>  x and y must be of same length. 
``` 

Could you also please explain the 'y_ ' argument? did you name the function y_ because y is already taken? Am a bit new to R.

Thanks so much

**Comment by DavZim** [comment]
For me the following works:

``` r
library(RTransferEntropy)

set.seed(123)
N <- 1000
k <- 10

x <- rnorm(N)
y <- matrix (rnorm(N * k), nrow = N, ncol = k, byrow = TRUE)
res <- apply(y, 2, function(y_) calc_te(x, y_, lx = 1, ly = 1, q = 0.1, 
                                        entropy = "Shannon", shuffles = 100, type = "quantiles", 
                                        quantiles = c(5, 95), bins = NULL, limits = NULL, burn = 50, seed = NULL, 
                                        na.rm = TRUE))
res
#>  [1] 0.003448776 0.004785991 0.003690248 0.006386847 0.002294250 0.008065925
#>  [7] 0.005742032 0.007249519 0.003633402 0.006854782
```

<sup>Created on 2020-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Your error originates as your matrix only has 2 rows, whereas x as 3 elements, thus they cannot be compared and the function throws an error.
