### ISSUE TITLE
Compute transfer entropy between two discrete Markov processes

### ISSUE THREAD

**Issue by emabe** [BZPaper/RTransferEntropy#53]
Hello,

assuming that I have two sequences X and Y, both Markov processes with state space in c(0, 1, 2, 3), how can I use your package to compute the transfer entropy?

I would use transfer_entropy(X, Y, type="limits", limits=c(0, 1, 2, 3)). Can you please confirm that the intuition is correct? Or am I clashing more classes together?

Thanks!

**Comment by DavZim** [comment]
Hi emabe,
Ill try to answer your question and your questions from the email:
- transfer entropy is non-linear, thus i believe it can be zero even though the correlation is high. This is partly do to the use of lags (see also the lag parameters in the function).
- For the same reason, you do not have to use `transfer_entropy(X, lag(Y))` but can use `transfer_entropy(X, Y)` directly, which computes X->Y as well as Y->X.
- correct, markov probabilities are calculated base on occurrences (see also function [`calculate_transition_probabilities()`](https://github.com/BZPaper/RTransferEntropy/blob/master/src/calculate_transition_probabilities.cpp) and [`bootstrap_shannon()`](https://github.com/BZPaper/RTransferEntropy/blob/master/R/bootstrap_shannon.R) both called internally from `transfer_entropy()`.
- Extracting the probabilities is not supported at the moment, but should be doable by looking at the [`cluster_gen()`](https://github.com/BZPaper/RTransferEntropy/blob/master/src/cluster_gen.cpp) function.
- Rolling windows does not make sense, unless you want to somehow downsample the data if you have issues with large data
- The way I understand you question, your code regarding the limits is correct.

Hope that helps!
