### ISSUE TITLE
pvalue and standard error calculations inverted

### ISSUE THREAD

**Issue by caioestevao** [BZPaper/RTransferEntropy#54]
In the transfer_entropy.R file, from line 274 where the pvalues and standard errors are being calculated, you have the following

    seteyx <- sd(te$boot[1, ])
    setexy <- sd(te$boot[2, ])

    pval <- function(x, est) length(x[x > est]) / length(x)
    psteyx <- pval(te$boot[1, ], te$teyx)
    pstexy <- pval(te$boot[2, ], te$texy)

The problem here, is that you're using indices rather than the names and maybe this is intentional. But  the first index in boot is actually dtexy and the second index of boot is dteyx. So dtexy is being used to calculate both the se and the pval for teyx and vice versa?

**Comment by DavZim** [comment]
Hi Caioestevao,
thanks for pointing this out and briefly looking into it.
I do agree that the naming and indexing by value rather than names is a bit - erm - suboptimal... However, the switcheroo seems to be double, that is, in the end it returns correct results. Or in other words, psteyx refers to Y->X and not X->Y...
As a quick sanity check, when looking at the example code from the Readme, we see a significance from X->Y, which is what was simulated.
We might "fix" in a potential future release, but I don't have the time to change this now.
In the meantime, if you want, I would be very happy to get a short Pull Request that changes the index to names and changes the names to the more intuitive pstexy := X->Y form.
I will close this now, if you need, feel free to reopen!

**Comment by caioestevao** [comment]
I understand that psteyx refers to Y->X and not X->Y. 

what I meant was, when you are calculating the pvalue and the standard error for X -> Y, which would be texy, you should be using the bootstrapped TE for X->Y right? but instead what you have is:

```{r}
pstexy <- pval(te$boot[2, ], te$texy)
```

and te$boot[2, ] is actually dteyx, so you are using the bootstrapped TE for Y->X to calculate the pvalue for X->Y. 

I ran the example code in the Readme:

```{r}
set.seed(1234567890)
n <- 500
x <- rep(0, n + 1)
y <- rep(0, n + 1)

for (i in seq(n)) {
  x[i + 1] <- 0.2 * x[i] + rnorm(1, 0, 2)
  y[i + 1] <- x[i] + rnorm(1, 0, 2)
}

x <- x[-1]
y <- y[-1]

te_result <- transfer_entropy(x, y, nboot = 100)
te_result

```

 and made the following changes:

```{r}
    seteyx <- sd(te$boot[2, ])
    setexy <- sd(te$boot[1, ])

    pval <- function(x, est) length(x[x > est]) / length(x)
    psteyx <- pval(te$boot[2, ], te$teyx)
    pstexy <- pval(te$boot[1, ], te$texy)
```

and you still get a significant X->Y
```{r}
Shannon Transfer Entropy Results:
-----------------------------------------------------------
Direction        TE   Eff. TE  Std.Err.   p-value    sig
-----------------------------------------------------------
     X->Y    0.1669    0.1564    0.0053    0.0000    ***
     Y->X    0.0090    0.0000    0.0049    0.5000       
-----------------------------------------------------------
Bootstrapped TE Quantiles (100 replications):
-----------------------------------------------------------
Direction      0%     25%     50%     75%    100%
-----------------------------------------------------------
     X->Y  0.0027  0.0083  0.0105  0.0144  0.0269
     Y->X  0.0014  0.0070  0.0090  0.0130  0.0252
-----------------------------------------------------------
Number of Observations: 500
-----------------------------------------------------------
p-values: < 0.001 '***', < 0.01 '**', < 0.05 '*', < 0.1 '.' 
```

**Comment by DavZim** [comment]
Ah, now I see what you mean. I'll look into it when I find the time. If you need it urgently, a PR is always welcome.
Thanks for taking the time to clarify.

**Comment by geofurb** [comment]
Oh man, I really wish you had fixed this bug before I found it for myself.

**Comment by DavZim** [comment]
This should fix the problem. If this is not the case, please let me know!
